// SPDX-FileCopyrightText: Copyright (C) 2026 unlucio and the Bespok3d contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
import { describe, it, expect } from 'vitest'
import AdmZip from 'adm-zip'
import * as openpgp from 'openpgp'
import { verifiedPackageTrust, PackageRefusedError } from './verify-package'
import type { TrustAnchor } from './trust-anchors'
import type { MergedEntry } from '../registry/model'

// The org's private key is a CI secret that never comes near this repo, so every passing path here is
// exercised against key pairs generated by the test process and discarded with it.
interface ThrowawayPublisher {
  signingKey: openpgp.PrivateKey
  anchor: TrustAnchor
}

const generatedPublishers = new Map<string, Promise<ThrowawayPublisher>>()

async function generatePublisher(publisherName: string, tier: TrustAnchor['tier']): Promise<ThrowawayPublisher> {
  const userIDs = [{ name: publisherName, email: 'publisher@example.invalid' }]
  const generated = await openpgp.generateKey({ userIDs, format: 'object' })

  return { signingKey: generated.privateKey, anchor: { armoredKey: generated.publicKey.armor(), tier } }
}

// Key generation is the slowest thing in this file and each publisher is reused across cases, so a
// publisher is generated once per name and every later request awaits the same promise.
function throwawayPublisher(publisherName: string, tier: TrustAnchor['tier'] = 'project'): Promise<ThrowawayPublisher> {
  const alreadyGenerating = generatedPublishers.get(publisherName)
  if (alreadyGenerating) return alreadyGenerating
  const generating = generatePublisher(publisherName, tier)
  generatedPublishers.set(publisherName, generating)

  return generating
}

// The framing b3-builder writes into the archive: two-space indent, trailing newline. The signature
// covers exactly these bytes, so the fixture must produce them rather than any equivalent JSON.
function manifestBytes(manifest: Record<string, unknown>): Buffer {
  return Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`, 'utf8')
}

async function detachedSignature(signedBytes: Buffer, signingKey: openpgp.PrivateKey): Promise<Buffer> {
  const message = await openpgp.createMessage({ binary: signedBytes })
  const armored = await openpgp.sign({ message, signingKeys: signingKey, detached: true })

  return Buffer.from(armored as string, 'utf8')
}

function packArchive(members: Record<string, Buffer>): Buffer {
  const archive = new AdmZip()
  Object.entries(members).forEach(([memberName, bytes]) => archive.addFile(memberName, bytes))

  return archive.toBuffer()
}

const IDLE_TIMEOUT_MANIFEST = {
  name: 'idle-timeout',
  version: '0.2.0',
  install: { config: { 'main.cfg': 'config/main.cfg' } },
  files: [{ path: 'config/main.cfg', sha256: 'f'.repeat(64) }],
}

const PAYLOAD_MEMBER = { 'config/main.cfg': Buffer.from('# obviously fake payload\n', 'utf8') }

async function signedPackage(manifest: Record<string, unknown>, publisher: ThrowawayPublisher): Promise<Buffer> {
  const bytes = manifestBytes(manifest)

  return packArchive({ 'manifest.json': bytes, 'manifest.json.sig': await detachedSignature(bytes, publisher.signingKey), ...PAYLOAD_MEMBER })
}

function unsignedPackage(manifest: Record<string, unknown>): Buffer {
  return packArchive({ 'manifest.json': manifestBytes(manifest), ...PAYLOAD_MEMBER })
}

function listedEntry(fields: Partial<MergedEntry> = {}): MergedEntry {
  return { name: 'idle-timeout', version: '0.2.0', trust: 'project', signer: null, registry_url: '/registry/index.json', ...fields }
}

describe('verifiedPackageTrust signature checking', () => {
  it('returns the tier of the anchor whose key signed the packed manifest bytes', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const archive = await signedPackage(IDLE_TIMEOUT_MANIFEST, publisher)
    expect(await verifiedPackageTrust(archive, listedEntry(), [publisher.anchor])).toBe('project')
  })

  // NO-DOWNGRADE: an unsigned package is missing proof, not failed proof. It still installs, at the
  // tier that says so, because refusing it would break every package built before signing existed.
  it('installs an unsigned package at tier unknown rather than refusing it', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const archive = unsignedPackage(IDLE_TIMEOUT_MANIFEST)
    expect(await verifiedPackageTrust(archive, listedEntry(), [publisher.anchor])).toBe('unknown')
  })

  it('refuses a package whose manifest was edited after it was signed', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const signature = await detachedSignature(manifestBytes(IDLE_TIMEOUT_MANIFEST), publisher.signingKey)
    const edited = manifestBytes({ ...IDLE_TIMEOUT_MANIFEST, install: { config: { 'main.cfg': 'config/attacker.cfg' } } })
    const archive = packArchive({ 'manifest.json': edited, 'manifest.json.sig': signature, ...PAYLOAD_MEMBER })
    await expect(verifiedPackageTrust(archive, listedEntry(), [publisher.anchor])).rejects.toThrow(PackageRefusedError)
  })

  it('refuses a sound signature issued by a key that is not in the anchor set', async () => {
    const stranger = await throwawayPublisher('Unanchored Stranger')
    const anchored = await throwawayPublisher('Anchored Publisher')
    const archive = await signedPackage(IDLE_TIMEOUT_MANIFEST, stranger)
    await expect(verifiedPackageTrust(archive, listedEntry(), [anchored.anchor])).rejects.toThrow(/does not check out/)
  })

  it('refuses a package carrying a signature openpgp cannot even parse', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const malformed = Buffer.from('-----BEGIN PGP SIGNATURE-----\n\nnot actually a signature\n-----END PGP SIGNATURE-----\n', 'utf8')
    const archive = packArchive({ 'manifest.json': manifestBytes(IDLE_TIMEOUT_MANIFEST), 'manifest.json.sig': malformed, ...PAYLOAD_MEMBER })
    await expect(verifiedPackageTrust(archive, listedEntry(), [publisher.anchor])).rejects.toThrow(PackageRefusedError)
  })
})

describe('verifiedPackageTrust anchor set', () => {
  // The set is plural so a key rotation can trust the outgoing and incoming keys at once. A package
  // signed by a later member must verify exactly as well as one signed by the first.
  it('accepts a package signed by a later member of the anchor set', async () => {
    const official = await throwawayPublisher('Anchored Publisher')
    const contributor = await throwawayPublisher('Community Publisher', 'community')
    const archive = await signedPackage(IDLE_TIMEOUT_MANIFEST, contributor)
    expect(await verifiedPackageTrust(archive, listedEntry(), [official.anchor, contributor.anchor])).toBe('community')
  })

  it('confers the tier of the matching anchor, not of the first one in the set', async () => {
    const official = await throwawayPublisher('Anchored Publisher')
    const contributor = await throwawayPublisher('Community Publisher', 'community')
    const archive = await signedPackage(IDLE_TIMEOUT_MANIFEST, official)
    expect(await verifiedPackageTrust(archive, listedEntry(), [contributor.anchor, official.anchor])).toBe('project')
  })

  it('refuses everything when the anchor set is empty', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const archive = await signedPackage(IDLE_TIMEOUT_MANIFEST, publisher)
    await expect(verifiedPackageTrust(archive, listedEntry(), [])).rejects.toThrow(PackageRefusedError)
  })
})

describe('verifiedPackageTrust payload enumeration', () => {
  // A signature over a manifest that enumerates nothing vouches for nothing that gets installed: the
  // package would look trustworthy while its actual payload rode along uncovered.
  it('refuses a signed package whose manifest has no files list', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const { files: _dropped, ...withoutFiles } = IDLE_TIMEOUT_MANIFEST
    const archive = await signedPackage(withoutFiles, publisher)
    await expect(verifiedPackageTrust(archive, listedEntry(), [publisher.anchor])).rejects.toThrow(/lists no files/)
  })

  it('refuses a signed package whose files list is empty', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const archive = await signedPackage({ ...IDLE_TIMEOUT_MANIFEST, files: [] }, publisher)
    await expect(verifiedPackageTrust(archive, listedEntry(), [publisher.anchor])).rejects.toThrow(/lists no files/)
  })

  it('refuses a package with no manifest.json at all', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    await expect(verifiedPackageTrust(packArchive(PAYLOAD_MEMBER), listedEntry(), [publisher.anchor])).rejects.toThrow(/no manifest.json/)
  })
})

describe('verifiedPackageTrust binding to the chosen catalog entry', () => {
  // A valid signature alone is not enough: a correctly signed package of a DIFFERENT plugin would
  // otherwise install in place of the one the user asked for.
  it('refuses a validly signed package that contains a different plugin', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const archive = await signedPackage({ ...IDLE_TIMEOUT_MANIFEST, name: 'camera' }, publisher)
    await expect(verifiedPackageTrust(archive, listedEntry(), [publisher.anchor])).rejects.toThrow(/contains plugin "camera"/)
  })

  it('refuses a version below the one the index listed, even validly signed', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const archive = await signedPackage({ ...IDLE_TIMEOUT_MANIFEST, version: '0.1.9' }, publisher)
    await expect(verifiedPackageTrust(archive, listedEntry({ version: '0.2.0' }), [publisher.anchor])).rejects.toThrow(/older than the listed/)
  })

  // The binding does not depend on a signature, so stripping the signature is not a way around it.
  it('refuses a downgraded unsigned package too', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const archive = unsignedPackage({ ...IDLE_TIMEOUT_MANIFEST, version: '0.1.9' })
    await expect(verifiedPackageTrust(archive, listedEntry({ version: '0.2.0' }), [publisher.anchor])).rejects.toThrow(PackageRefusedError)
  })

  it('accepts a package newer than the listing, which is not a downgrade', async () => {
    const publisher = await throwawayPublisher('Anchored Publisher')
    const archive = await signedPackage({ ...IDLE_TIMEOUT_MANIFEST, version: '0.3.0' }, publisher)
    expect(await verifiedPackageTrust(archive, listedEntry({ version: '0.2.0' }), [publisher.anchor])).toBe('project')
  })
})
