// SPDX-FileCopyrightText: Copyright (C) 2026 unlucio and the Bespok3d contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
import { describe, it, expect } from 'vitest'
// @ts-expect-error - build-time generator, plain JS with no type declarations
import { parseExports, buildInventory } from '../../../../../scripts/component-inventory.mjs'

describe('component-inventory parseExports', () => {
  it('classifies exported components and hooks, ignoring helpers and types', () => {
    const text = `// A row primitive.
export function Row() { return null }
export function useClipboard() { return {} }
function internalHelper() {}
export const TIMEOUT = 5
export type RowProps = { x: number }`
    expect(parseExports(text)).toEqual([
      { name: 'Row', kind: 'component', purpose: 'A row primitive.' },
      { name: 'useClipboard', kind: 'hook', purpose: '' },
    ])
  })

  it('takes the LEAD line of a multi-line comment block as the purpose', () => {
    const text = `// The one modal scaffold.
// Tail line that should not become the purpose.
export function Modal() { return null }`
    expect(parseExports(text)[0].purpose).toBe('The one modal scaffold.')
  })

  it('leaves the purpose blank when the line above is not a comment', () => {
    const text = `interface Props { a: number }
export function Button() { return null }`
    expect(parseExports(text)[0].purpose).toBe('')
  })
})

describe('component-inventory buildInventory', () => {
  it('groups entries by area and renders a generated-file banner', () => {
    const markdown = buildInventory([
      { path: 'components/common/Button.tsx', entries: [{ name: 'Button', kind: 'component', purpose: '' }] },
      { path: 'hooks/useThing.ts', entries: [{ name: 'useThing', kind: 'hook', purpose: 'Does the thing.' }] },
    ])
    expect(markdown).toContain('GENERATED by `scripts/component-inventory.mjs`')
    expect(markdown).toContain('## Common primitives')
    expect(markdown).toContain('## Hooks')
    expect(markdown).toContain('`useThing` (hook)')
    expect(markdown).toContain('Does the thing.')
  })
})
